// <auto-generated />
using System;
using Calory.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Calory.Persistance.Migrations
{
    [DbContext(typeof(CaloryDbContext))]
    partial class CaloryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Calory.Domain.FoodEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ConsumedAt");

                    b.ToTable("FoodEntries");
                });

            modelBuilder.Entity("Calory.Domain.FoodNutrition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CalciumMg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Calories")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("CarbohydratesG")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("FatG")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("FiberG")
                        .HasColumnType("numeric");

                    b.Property<Guid>("FoodEntryId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("IronMg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MagnesiumMg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PotassiumMg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ProteinG")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("SodiumMg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SugarG")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VitaminAMcg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VitaminB12Mcg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VitaminB1Mg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VitaminB2Mg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VitaminB3Mg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VitaminB6Mg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VitaminCMg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VitaminDMcg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VitaminEMg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VitaminKMcg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ZincMg")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("FoodEntryId")
                        .IsUnique();

                    b.ToTable("FoodNutrition");
                });

            modelBuilder.Entity("Calory.Domain.HealthGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CarbTarget")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DailyCalorieTarget")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<decimal>("FatTarget")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ProteinTarget")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("WeightTarget")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("HealthGoals");
                });

            modelBuilder.Entity("Calory.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Calory.Domain.FoodNutrition", b =>
                {
                    b.HasOne("Calory.Domain.FoodEntry", null)
                        .WithOne("Nutrition")
                        .HasForeignKey("Calory.Domain.FoodNutrition", "FoodEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Calory.Domain.FoodEntry", b =>
                {
                    b.Navigation("Nutrition")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
